import tkinter
from tkinter import *
from tkinter import ttk
t=tkinter.Tk()
t.geometry('700x700')
t.title('make new page')
a=Label(t,text='Registration form')
a.place(x=300,y=10)
b=Label(t,text='Name')
b.place(x=30,y=60)
d=Entry(t,width=30)
d.place(x=350,y=60)
e=Label(t,text='Password')
e.place(x=30,y=100)
f=Entry(t,width=30,show='*')
f.place(x=350,y=100)
g=Label(t,text='Age')
g.place(x=30,y=140)
sp=Spinbox(t,from_=18,to=60)
sp.place(x=350,y=140)
h=Label(t,text='City')
h.place(x=30,y=180)
cb=ttk.Combobox(t)
cb['values']=['delhi','noida','agra','pune','mathura','aligarh','allahbad']
cb.place(x=350,y=180)
j=Label(t,text='Skills')
j.place(x=30,y=220)
m=Listbox(t,height=4)
m.insert(1,'python')
m.insert(2,'java')
m.insert(3,'excel')
m.insert(4,'c++')
m.place(x=350,y=220)
bt=Button(t,text='Save')
bt.place(x=300,y=500)
t.mainloop()